"""add_customer_columns

Revision ID: 0439fdabfa05
Revises: 62bc842a4881
Create Date: 2026-08-05 12:02:13.054997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0439fdabfa05'
down_revision: Union[str, Sequence[str], None] = '62bc842a4881'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clientes', sa.Column('tenant_id', sa.UUID(), server_default='00000000-0000-0000-0000-000000000000', nullable=False))
    op.add_column('clientes', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('clientes', sa.Column('code', sa.String(length=100), server_default='LEGADO', nullable=False))
    op.add_column('clientes', sa.Column('row_version', sa.Integer(), server_default='1', nullable=False))
    op.add_column('clientes', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))

    op.execute("UPDATE clientes SET nome = 'Cliente Legado Sem Nome' WHERE nome IS NULL")
    op.execute("UPDATE clientes SET tipo_pessoa = 'INDIVIDUAL' WHERE tipo_pessoa IS NULL")
    op.execute("UPDATE clientes SET ativo = true WHERE ativo IS NULL")
    op.execute("UPDATE clientes SET data_cadastro = now() WHERE data_cadastro IS NULL")

    op.alter_column('clientes', 'nome',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('clientes', 'tipo_pessoa',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('clientes', 'ativo',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('clientes', 'data_cadastro',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False)
    op.drop_index(op.f('ix_clientes_id'), table_name='clientes')
    op.create_index(op.f('ix_clientes_tenant_id'), 'clientes', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clientes_tenant_id'), table_name='clientes')
    op.create_index(op.f('ix_clientes_id'), 'clientes', ['id'], unique=False)
    op.alter_column('clientes', 'data_cadastro',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('clientes', 'ativo',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('clientes', 'tipo_pessoa',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('clientes', 'nome',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('clientes', 'deleted_at')
    op.drop_column('clientes', 'row_version')
    op.drop_column('clientes', 'code')
    op.drop_column('clientes', 'updated_at')
    op.drop_column('clientes', 'tenant_id')
    # ### end Alembic commands ###
