"""Create the tenant-scoped production core.

Revision ID: 49b92745c01a
Revises: 63f6df64a945
Create Date: 2026-08-07 15:13:29.723631
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

revision: str = "49b92745c01a"
down_revision: str | Sequence[str] | None = "63f6df64a945"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Create the modern production core."""

    # Composite tenant-safe foreign keys in the production domain require
    # these candidate keys to exist before the referencing tables.
    op.create_unique_constraint(
        "uq_employees_id_tenant",
        "employees",
        [
            "id",
            "tenant_id",
        ],
    )

    op.create_unique_constraint(
        "uq_machines_id_tenant",
        "machines",
        [
            "id",
            "tenant_id",
        ],
    )

    op.create_unique_constraint(
        "uq_services_id_tenant",
        "services",
        [
            "id",
            "tenant_id",
        ],
    )

    op.create_table(
        "production_orders",
        sa.Column(
            "branch_id",
            sa.Uuid(),
            nullable=True,
        ),
        sa.Column(
            "code",
            sa.String(length=100),
            nullable=False,
        ),
        sa.Column(
            "title",
            sa.String(length=255),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.String(length=30),
            server_default=sa.text("'PLANNED'"),
            nullable=False,
        ),
        sa.Column(
            "priority",
            sa.String(length=20),
            server_default=sa.text("'NORMAL'"),
            nullable=False,
        ),
        sa.Column(
            "planned_start_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "planned_end_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "is_active",
            sa.Boolean(),
            server_default=sa.text("true"),
            nullable=False,
        ),
        sa.Column(
            "id",
            sa.UUID(),
            nullable=False,
        ),
        sa.Column(
            "tenant_id",
            sa.UUID(),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.CheckConstraint(
            "TRIM(code) <> ''",
            name=op.f(
                "ck_production_orders_code_not_blank"
            ),
        ),
        sa.CheckConstraint(
            (
                "planned_end_at IS NULL "
                "OR planned_start_at IS NULL "
                "OR planned_end_at >= planned_start_at"
            ),
            name=op.f(
                "ck_production_orders_planning_dates_valid"
            ),
        ),
        sa.CheckConstraint(
            (
                "priority IN "
                "('LOW', 'NORMAL', 'HIGH', 'URGENT')"
            ),
            name=op.f(
                "ck_production_orders_priority_valid"
            ),
        ),
        sa.CheckConstraint(
            (
                "status IN "
                "('PLANNED', 'RELEASED', "
                "'IN_PROGRESS', 'PAUSED', "
                "'COMPLETED', 'CANCELLED')"
            ),
            name=op.f(
                "ck_production_orders_status_valid"
            ),
        ),
        sa.CheckConstraint(
            "TRIM(title) <> ''",
            name=op.f(
                "ck_production_orders_title_not_blank"
            ),
        ),
        sa.ForeignKeyConstraint(
            [
                "branch_id",
                "tenant_id",
            ],
            [
                "branches.id",
                "branches.tenant_id",
            ],
            name="fk_production_orders_branch_tenant",
        ),
        sa.ForeignKeyConstraint(
            [
                "tenant_id",
            ],
            [
                "tenants.id",
            ],
            name=op.f(
                "fk_production_orders_tenant_id_tenants"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "id",
            name=op.f(
                "pk_production_orders"
            ),
        ),
        sa.UniqueConstraint(
            "id",
            "tenant_id",
            name="uq_production_orders_id_tenant",
        ),
        sa.UniqueConstraint(
            "tenant_id",
            "code",
            name="uq_production_orders_tenant_code",
        ),
    )

    op.create_index(
        "ix_production_orders_tenant_active",
        "production_orders",
        [
            "tenant_id",
            "is_active",
        ],
        unique=False,
    )

    op.create_index(
        "ix_production_orders_tenant_branch",
        "production_orders",
        [
            "tenant_id",
            "branch_id",
        ],
        unique=False,
    )

    op.create_index(
        op.f("ix_production_orders_tenant_id"),
        "production_orders",
        [
            "tenant_id",
        ],
        unique=False,
    )

    op.create_index(
        "ix_production_orders_tenant_priority",
        "production_orders",
        [
            "tenant_id",
            "priority",
        ],
        unique=False,
    )

    op.create_index(
        "ix_production_orders_tenant_status",
        "production_orders",
        [
            "tenant_id",
            "status",
        ],
        unique=False,
    )

    op.create_table(
        "production_operations",
        sa.Column(
            "production_order_id",
            sa.Uuid(),
            nullable=False,
        ),
        sa.Column(
            "sequence",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "name",
            sa.String(length=255),
            nullable=False,
        ),
        sa.Column(
            "service_id",
            sa.Uuid(),
            nullable=True,
        ),
        sa.Column(
            "machine_id",
            sa.Uuid(),
            nullable=True,
        ),
        sa.Column(
            "status",
            sa.String(length=30),
            server_default=sa.text("'PENDING'"),
            nullable=False,
        ),
        sa.Column(
            "is_applicable",
            sa.Boolean(),
            server_default=sa.text("true"),
            nullable=False,
        ),
        sa.Column(
            "id",
            sa.UUID(),
            nullable=False,
        ),
        sa.Column(
            "tenant_id",
            sa.UUID(),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.CheckConstraint(
            (
                "(is_applicable = true "
                "AND status <> 'NOT_APPLICABLE') "
                "OR "
                "(is_applicable = false "
                "AND status = 'NOT_APPLICABLE')"
            ),
            name=op.f(
                "ck_production_operations_"
                "applicability_status_consistent"
            ),
        ),
        sa.CheckConstraint(
            "TRIM(name) <> ''",
            name=op.f(
                "ck_production_operations_name_not_blank"
            ),
        ),
        sa.CheckConstraint(
            "sequence > 0",
            name=op.f(
                "ck_production_operations_sequence_positive"
            ),
        ),
        sa.CheckConstraint(
            (
                "status IN "
                "('PENDING', 'READY', "
                "'IN_PROGRESS', 'PAUSED', "
                "'COMPLETED', 'NOT_APPLICABLE', "
                "'CANCELLED')"
            ),
            name=op.f(
                "ck_production_operations_status_valid"
            ),
        ),
        sa.ForeignKeyConstraint(
            [
                "machine_id",
                "tenant_id",
            ],
            [
                "machines.id",
                "machines.tenant_id",
            ],
            name=(
                "fk_production_operations_machine_tenant"
            ),
        ),
        sa.ForeignKeyConstraint(
            [
                "production_order_id",
                "tenant_id",
            ],
            [
                "production_orders.id",
                "production_orders.tenant_id",
            ],
            name=(
                "fk_production_operations_order_tenant"
            ),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            [
                "service_id",
                "tenant_id",
            ],
            [
                "services.id",
                "services.tenant_id",
            ],
            name=(
                "fk_production_operations_service_tenant"
            ),
        ),
        sa.ForeignKeyConstraint(
            [
                "tenant_id",
            ],
            [
                "tenants.id",
            ],
            name=op.f(
                "fk_production_operations_tenant_id_tenants"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "id",
            name=op.f(
                "pk_production_operations"
            ),
        ),
        sa.UniqueConstraint(
            "id",
            "production_order_id",
            "tenant_id",
            name=(
                "uq_production_operations_id_order_tenant"
            ),
        ),
        sa.UniqueConstraint(
            "id",
            "tenant_id",
            name="uq_production_operations_id_tenant",
        ),
        sa.UniqueConstraint(
            "production_order_id",
            "sequence",
            name=(
                "uq_production_operations_order_sequence"
            ),
        ),
    )

    op.create_index(
        op.f("ix_production_operations_tenant_id"),
        "production_operations",
        [
            "tenant_id",
        ],
        unique=False,
    )

    op.create_index(
        "ix_production_operations_tenant_machine",
        "production_operations",
        [
            "tenant_id",
            "machine_id",
        ],
        unique=False,
    )

    op.create_index(
        "ix_production_operations_tenant_order",
        "production_operations",
        [
            "tenant_id",
            "production_order_id",
        ],
        unique=False,
    )

    op.create_index(
        "ix_production_operations_tenant_service",
        "production_operations",
        [
            "tenant_id",
            "service_id",
        ],
        unique=False,
    )

    op.create_index(
        "ix_production_operations_tenant_status",
        "production_operations",
        [
            "tenant_id",
            "status",
        ],
        unique=False,
    )

    op.create_table(
        "production_executions",
        sa.Column(
            "operation_id",
            sa.Uuid(),
            nullable=False,
        ),
        sa.Column(
            "employee_id",
            sa.Uuid(),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.String(length=20),
            server_default=sa.text("'RUNNING'"),
            nullable=False,
        ),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "finished_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "id",
            sa.UUID(),
            nullable=False,
        ),
        sa.Column(
            "tenant_id",
            sa.UUID(),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.CheckConstraint(
            (
                "(status = 'COMPLETED' "
                "AND finished_at IS NOT NULL) "
                "OR "
                "(status <> 'COMPLETED')"
            ),
            name=op.f(
                "ck_production_executions_"
                "completed_has_finished_at"
            ),
        ),
        sa.CheckConstraint(
            (
                "finished_at IS NULL "
                "OR finished_at >= started_at"
            ),
            name=op.f(
                "ck_production_executions_execution_dates_valid"
            ),
        ),
        sa.CheckConstraint(
            (
                "status IN "
                "('RUNNING', 'PAUSED', "
                "'COMPLETED', 'CANCELLED')"
            ),
            name=op.f(
                "ck_production_executions_status_valid"
            ),
        ),
        sa.ForeignKeyConstraint(
            [
                "employee_id",
                "tenant_id",
            ],
            [
                "employees.id",
                "employees.tenant_id",
            ],
            name=(
                "fk_production_executions_employee_tenant"
            ),
        ),
        sa.ForeignKeyConstraint(
            [
                "operation_id",
                "tenant_id",
            ],
            [
                "production_operations.id",
                "production_operations.tenant_id",
            ],
            name=(
                "fk_production_executions_operation_tenant"
            ),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            [
                "tenant_id",
            ],
            [
                "tenants.id",
            ],
            name=op.f(
                "fk_production_executions_tenant_id_tenants"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "id",
            name=op.f(
                "pk_production_executions"
            ),
        ),
        sa.UniqueConstraint(
            "id",
            "operation_id",
            "tenant_id",
            name=(
                "uq_production_executions_"
                "id_operation_tenant"
            ),
        ),
        sa.UniqueConstraint(
            "id",
            "tenant_id",
            name=(
                "uq_production_executions_id_tenant"
            ),
        ),
    )

    op.create_index(
        "ix_production_executions_tenant_employee",
        "production_executions",
        [
            "tenant_id",
            "employee_id",
        ],
        unique=False,
    )

    op.create_index(
        op.f("ix_production_executions_tenant_id"),
        "production_executions",
        [
            "tenant_id",
        ],
        unique=False,
    )

    op.create_index(
        "ix_production_executions_tenant_operation",
        "production_executions",
        [
            "tenant_id",
            "operation_id",
        ],
        unique=False,
    )

    op.create_index(
        "ix_production_executions_tenant_started",
        "production_executions",
        [
            "tenant_id",
            "started_at",
        ],
        unique=False,
    )

    op.create_index(
        "ix_production_executions_tenant_status",
        "production_executions",
        [
            "tenant_id",
            "status",
        ],
        unique=False,
    )

    op.create_table(
        "production_events",
        sa.Column(
            "production_order_id",
            sa.Uuid(),
            nullable=False,
        ),
        sa.Column(
            "operation_id",
            sa.Uuid(),
            nullable=True,
        ),
        sa.Column(
            "execution_id",
            sa.Uuid(),
            nullable=True,
        ),
        sa.Column(
            "employee_id",
            sa.Uuid(),
            nullable=True,
        ),
        sa.Column(
            "event_type",
            sa.String(length=100),
            nullable=False,
        ),
        sa.Column(
            "reason_code",
            sa.String(length=100),
            nullable=True,
        ),
        sa.Column(
            "notes",
            sa.String(length=2000),
            nullable=True,
        ),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "id",
            sa.UUID(),
            nullable=False,
        ),
        sa.Column(
            "tenant_id",
            sa.UUID(),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.CheckConstraint(
            "TRIM(event_type) <> ''",
            name=op.f(
                "ck_production_events_event_type_not_blank"
            ),
        ),
        sa.CheckConstraint(
            (
                "execution_id IS NULL "
                "OR operation_id IS NOT NULL"
            ),
            name=op.f(
                "ck_production_events_"
                "execution_requires_operation"
            ),
        ),
        sa.ForeignKeyConstraint(
            [
                "employee_id",
                "tenant_id",
            ],
            [
                "employees.id",
                "employees.tenant_id",
            ],
            name=(
                "fk_production_events_employee_tenant"
            ),
        ),
        sa.ForeignKeyConstraint(
            [
                "execution_id",
                "operation_id",
                "tenant_id",
            ],
            [
                "production_executions.id",
                "production_executions.operation_id",
                "production_executions.tenant_id",
            ],
            name=(
                "fk_production_events_"
                "execution_operation_tenant"
            ),
        ),
        sa.ForeignKeyConstraint(
            [
                "operation_id",
                "production_order_id",
                "tenant_id",
            ],
            [
                "production_operations.id",
                "production_operations.production_order_id",
                "production_operations.tenant_id",
            ],
            name=(
                "fk_production_events_"
                "operation_order_tenant"
            ),
        ),
        sa.ForeignKeyConstraint(
            [
                "production_order_id",
                "tenant_id",
            ],
            [
                "production_orders.id",
                "production_orders.tenant_id",
            ],
            name="fk_production_events_order_tenant",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            [
                "tenant_id",
            ],
            [
                "tenants.id",
            ],
            name=op.f(
                "fk_production_events_tenant_id_tenants"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "id",
            name=op.f(
                "pk_production_events"
            ),
        ),
    )

    op.create_index(
        "ix_production_events_tenant_employee",
        "production_events",
        [
            "tenant_id",
            "employee_id",
        ],
        unique=False,
    )

    op.create_index(
        "ix_production_events_tenant_execution",
        "production_events",
        [
            "tenant_id",
            "execution_id",
        ],
        unique=False,
    )

    op.create_index(
        op.f("ix_production_events_tenant_id"),
        "production_events",
        [
            "tenant_id",
        ],
        unique=False,
    )

    op.create_index(
        "ix_production_events_tenant_occurred",
        "production_events",
        [
            "tenant_id",
            "occurred_at",
        ],
        unique=False,
    )

    op.create_index(
        "ix_production_events_tenant_operation",
        "production_events",
        [
            "tenant_id",
            "operation_id",
        ],
        unique=False,
    )

    op.create_index(
        "ix_production_events_tenant_order",
        "production_events",
        [
            "tenant_id",
            "production_order_id",
        ],
        unique=False,
    )

    op.create_index(
        "ix_production_events_tenant_type",
        "production_events",
        [
            "tenant_id",
            "event_type",
        ],
        unique=False,
    )

    op.create_table(
        "production_pauses",
        sa.Column(
            "execution_id",
            sa.Uuid(),
            nullable=False,
        ),
        sa.Column(
            "reason_code",
            sa.String(length=100),
            nullable=False,
        ),
        sa.Column(
            "notes",
            sa.String(length=1000),
            nullable=True,
        ),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "ended_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "id",
            sa.UUID(),
            nullable=False,
        ),
        sa.Column(
            "tenant_id",
            sa.UUID(),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.CheckConstraint(
            (
                "ended_at IS NULL "
                "OR ended_at >= started_at"
            ),
            name=op.f(
                "ck_production_pauses_pause_dates_valid"
            ),
        ),
        sa.CheckConstraint(
            "TRIM(reason_code) <> ''",
            name=op.f(
                "ck_production_pauses_reason_code_not_blank"
            ),
        ),
        sa.ForeignKeyConstraint(
            [
                "execution_id",
                "tenant_id",
            ],
            [
                "production_executions.id",
                "production_executions.tenant_id",
            ],
            name=(
                "fk_production_pauses_execution_tenant"
            ),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            [
                "tenant_id",
            ],
            [
                "tenants.id",
            ],
            name=op.f(
                "fk_production_pauses_tenant_id_tenants"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "id",
            name=op.f(
                "pk_production_pauses"
            ),
        ),
    )

    op.create_index(
        "ix_production_pauses_tenant_execution",
        "production_pauses",
        [
            "tenant_id",
            "execution_id",
        ],
        unique=False,
    )

    op.create_index(
        op.f("ix_production_pauses_tenant_id"),
        "production_pauses",
        [
            "tenant_id",
        ],
        unique=False,
    )

    op.create_index(
        "ix_production_pauses_tenant_reason",
        "production_pauses",
        [
            "tenant_id",
            "reason_code",
        ],
        unique=False,
    )

    op.create_index(
        "ix_production_pauses_tenant_started",
        "production_pauses",
        [
            "tenant_id",
            "started_at",
        ],
        unique=False,
    )


def downgrade() -> None:
    """Remove the modern production core."""

    # Child tables must disappear before candidate keys used by their
    # composite foreign keys can be removed.

    op.drop_index(
        "ix_production_pauses_tenant_started",
        table_name="production_pauses",
    )
    op.drop_index(
        "ix_production_pauses_tenant_reason",
        table_name="production_pauses",
    )
    op.drop_index(
        op.f("ix_production_pauses_tenant_id"),
        table_name="production_pauses",
    )
    op.drop_index(
        "ix_production_pauses_tenant_execution",
        table_name="production_pauses",
    )
    op.drop_table(
        "production_pauses"
    )

    op.drop_index(
        "ix_production_events_tenant_type",
        table_name="production_events",
    )
    op.drop_index(
        "ix_production_events_tenant_order",
        table_name="production_events",
    )
    op.drop_index(
        "ix_production_events_tenant_operation",
        table_name="production_events",
    )
    op.drop_index(
        "ix_production_events_tenant_occurred",
        table_name="production_events",
    )
    op.drop_index(
        op.f("ix_production_events_tenant_id"),
        table_name="production_events",
    )
    op.drop_index(
        "ix_production_events_tenant_execution",
        table_name="production_events",
    )
    op.drop_index(
        "ix_production_events_tenant_employee",
        table_name="production_events",
    )
    op.drop_table(
        "production_events"
    )

    op.drop_index(
        "ix_production_executions_tenant_status",
        table_name="production_executions",
    )
    op.drop_index(
        "ix_production_executions_tenant_started",
        table_name="production_executions",
    )
    op.drop_index(
        "ix_production_executions_tenant_operation",
        table_name="production_executions",
    )
    op.drop_index(
        op.f("ix_production_executions_tenant_id"),
        table_name="production_executions",
    )
    op.drop_index(
        "ix_production_executions_tenant_employee",
        table_name="production_executions",
    )
    op.drop_table(
        "production_executions"
    )

    op.drop_index(
        "ix_production_operations_tenant_status",
        table_name="production_operations",
    )
    op.drop_index(
        "ix_production_operations_tenant_service",
        table_name="production_operations",
    )
    op.drop_index(
        "ix_production_operations_tenant_order",
        table_name="production_operations",
    )
    op.drop_index(
        "ix_production_operations_tenant_machine",
        table_name="production_operations",
    )
    op.drop_index(
        op.f("ix_production_operations_tenant_id"),
        table_name="production_operations",
    )
    op.drop_table(
        "production_operations"
    )

    op.drop_index(
        "ix_production_orders_tenant_status",
        table_name="production_orders",
    )
    op.drop_index(
        "ix_production_orders_tenant_priority",
        table_name="production_orders",
    )
    op.drop_index(
        op.f("ix_production_orders_tenant_id"),
        table_name="production_orders",
    )
    op.drop_index(
        "ix_production_orders_tenant_branch",
        table_name="production_orders",
    )
    op.drop_index(
        "ix_production_orders_tenant_active",
        table_name="production_orders",
    )
    op.drop_table(
        "production_orders"
    )

    op.drop_constraint(
        "uq_services_id_tenant",
        "services",
        type_="unique",
    )

    op.drop_constraint(
        "uq_machines_id_tenant",
        "machines",
        type_="unique",
    )

    op.drop_constraint(
        "uq_employees_id_tenant",
        "employees",
        type_="unique",
    )
