"""create finance core

Revision ID: 69e086a75bdb
Revises: 9189ddfdd4b1
Create Date: 2026-08-08 08:40:19.317457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69e086a75bdb'
down_revision: Union[str, Sequence[str], None] = '9189ddfdd4b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('financial_accounts',
    sa.Column('branch_id', sa.Uuid(), nullable=True),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('account_type', sa.String(length=30), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default=sa.text("'BRL'"), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("TRIM(code) <> ''", name=op.f('ck_financial_accounts_code_not_blank')),
    sa.CheckConstraint("TRIM(name) <> ''", name=op.f('ck_financial_accounts_name_not_blank')),
    sa.CheckConstraint("account_type IN ('CASH', 'BANK', 'CARD_CLEARING', 'OTHER')", name=op.f('ck_financial_accounts_account_type_valid')),
    sa.CheckConstraint('LENGTH(currency) = 3 AND currency = UPPER(currency)', name=op.f('ck_financial_accounts_currency_valid')),
    sa.ForeignKeyConstraint(['branch_id', 'tenant_id'], ['branches.id', 'branches.tenant_id'], name='fk_financial_accounts_branch_tenant'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_financial_accounts_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_financial_accounts')),
    sa.UniqueConstraint('id', 'tenant_id', name='uq_financial_accounts_id_tenant'),
    sa.UniqueConstraint('tenant_id', 'code', name='uq_financial_accounts_tenant_code')
    )
    op.create_index('ix_financial_accounts_tenant_active', 'financial_accounts', ['tenant_id', 'is_active'], unique=False)
    op.create_index('ix_financial_accounts_tenant_branch', 'financial_accounts', ['tenant_id', 'branch_id'], unique=False)
    op.create_index(op.f('ix_financial_accounts_tenant_id'), 'financial_accounts', ['tenant_id'], unique=False)
    op.create_index('ix_financial_accounts_tenant_type', 'financial_accounts', ['tenant_id', 'account_type'], unique=False)
    op.create_table('financial_transactions',
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('transaction_type', sa.String(length=30), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=False),
    sa.Column('status', sa.String(length=30), server_default=sa.text("'POSTED'"), nullable=False),
    sa.Column('payment_method', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.String(length=4000), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("(status <> 'CANCELLED') OR cancelled_at IS NOT NULL", name=op.f('ck_financial_transactions_cancelled_state_valid')),
    sa.CheckConstraint("TRIM(description) <> ''", name=op.f('ck_financial_transactions_description_not_blank')),
    sa.CheckConstraint("status IN ('POSTED', 'CANCELLED')", name=op.f('ck_financial_transactions_status_valid')),
    sa.CheckConstraint("transaction_type IN ('INFLOW', 'OUTFLOW')", name=op.f('ck_financial_transactions_transaction_type_valid')),
    sa.CheckConstraint('amount > 0', name=op.f('ck_financial_transactions_amount_positive')),
    sa.ForeignKeyConstraint(['account_id', 'tenant_id'], ['financial_accounts.id', 'financial_accounts.tenant_id'], name='fk_financial_transactions_account_tenant'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_financial_transactions_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_financial_transactions')),
    sa.UniqueConstraint('id', 'tenant_id', name='uq_financial_transactions_id_tenant')
    )
    op.create_index('ix_financial_transactions_tenant_account', 'financial_transactions', ['tenant_id', 'account_id'], unique=False)
    op.create_index(op.f('ix_financial_transactions_tenant_id'), 'financial_transactions', ['tenant_id'], unique=False)
    op.create_index('ix_financial_transactions_tenant_occurred', 'financial_transactions', ['tenant_id', 'occurred_at'], unique=False)
    op.create_index('ix_financial_transactions_tenant_type_status', 'financial_transactions', ['tenant_id', 'transaction_type', 'status'], unique=False)
    op.create_table('financial_entries',
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('entry_type', sa.String(length=30), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=30), server_default=sa.text("'OPEN'"), nullable=False),
    sa.Column('branch_id', sa.Uuid(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('supplier_id', sa.Uuid(), nullable=True),
    sa.Column('employee_id', sa.Uuid(), nullable=True),
    sa.Column('sales_order_id', sa.Uuid(), nullable=True),
    sa.Column('purchase_order_id', sa.Uuid(), nullable=True),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.String(length=4000), nullable=True),
    sa.Column('settled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("(entry_type <> 'PAYABLE') OR (customer_id IS NULL AND sales_order_id IS NULL)", name=op.f('ck_financial_entries_payable_direction_valid')),
    sa.CheckConstraint("(entry_type <> 'RECEIVABLE') OR (supplier_id IS NULL AND employee_id IS NULL AND purchase_order_id IS NULL)", name=op.f('ck_financial_entries_receivable_direction_valid')),
    sa.CheckConstraint("(status <> 'CANCELLED') OR cancelled_at IS NOT NULL", name=op.f('ck_financial_entries_cancelled_state_valid')),
    sa.CheckConstraint("(status <> 'SETTLED') OR settled_at IS NOT NULL", name=op.f('ck_financial_entries_settled_state_valid')),
    sa.CheckConstraint("TRIM(code) <> ''", name=op.f('ck_financial_entries_code_not_blank')),
    sa.CheckConstraint("TRIM(description) <> ''", name=op.f('ck_financial_entries_description_not_blank')),
    sa.CheckConstraint("entry_type IN ('RECEIVABLE', 'PAYABLE')", name=op.f('ck_financial_entries_entry_type_valid')),
    sa.CheckConstraint("status IN ('OPEN', 'PARTIALLY_SETTLED', 'SETTLED', 'CANCELLED')", name=op.f('ck_financial_entries_status_valid')),
    sa.CheckConstraint('amount > 0', name=op.f('ck_financial_entries_amount_positive')),
    sa.CheckConstraint('due_date >= issue_date', name=op.f('ck_financial_entries_dates_valid')),
    sa.ForeignKeyConstraint(['branch_id', 'tenant_id'], ['branches.id', 'branches.tenant_id'], name='fk_financial_entries_branch_tenant'),
    sa.ForeignKeyConstraint(['customer_id', 'tenant_id'], ['clientes.id', 'clientes.tenant_id'], name='fk_financial_entries_customer_tenant'),
    sa.ForeignKeyConstraint(['employee_id', 'tenant_id'], ['employees.id', 'employees.tenant_id'], name='fk_financial_entries_employee_tenant'),
    sa.ForeignKeyConstraint(['purchase_order_id', 'tenant_id'], ['purchase_orders.id', 'purchase_orders.tenant_id'], name='fk_financial_entries_purchase_order_tenant'),
    sa.ForeignKeyConstraint(['sales_order_id', 'tenant_id'], ['sales_orders.id', 'sales_orders.tenant_id'], name='fk_financial_entries_sales_order_tenant'),
    sa.ForeignKeyConstraint(['supplier_id', 'tenant_id'], ['suppliers.id', 'suppliers.tenant_id'], name='fk_financial_entries_supplier_tenant'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_financial_entries_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_financial_entries')),
    sa.UniqueConstraint('id', 'tenant_id', name='uq_financial_entries_id_tenant'),
    sa.UniqueConstraint('tenant_id', 'code', name='uq_financial_entries_tenant_code')
    )
    op.create_index('ix_financial_entries_tenant_branch', 'financial_entries', ['tenant_id', 'branch_id'], unique=False)
    op.create_index('ix_financial_entries_tenant_customer', 'financial_entries', ['tenant_id', 'customer_id'], unique=False)
    op.create_index('ix_financial_entries_tenant_due_date', 'financial_entries', ['tenant_id', 'due_date'], unique=False)
    op.create_index('ix_financial_entries_tenant_employee', 'financial_entries', ['tenant_id', 'employee_id'], unique=False)
    op.create_index(op.f('ix_financial_entries_tenant_id'), 'financial_entries', ['tenant_id'], unique=False)
    op.create_index('ix_financial_entries_tenant_purchase_order', 'financial_entries', ['tenant_id', 'purchase_order_id'], unique=False)
    op.create_index('ix_financial_entries_tenant_sales_order', 'financial_entries', ['tenant_id', 'sales_order_id'], unique=False)
    op.create_index('ix_financial_entries_tenant_supplier', 'financial_entries', ['tenant_id', 'supplier_id'], unique=False)
    op.create_index('ix_financial_entries_tenant_type_status', 'financial_entries', ['tenant_id', 'entry_type', 'status'], unique=False)
    op.create_table('financial_allocations',
    sa.Column('transaction_id', sa.Uuid(), nullable=False),
    sa.Column('entry_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('amount > 0', name=op.f('ck_financial_allocations_amount_positive')),
    sa.ForeignKeyConstraint(['entry_id', 'tenant_id'], ['financial_entries.id', 'financial_entries.tenant_id'], name='fk_financial_allocations_entry_tenant', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_financial_allocations_tenant_id_tenants'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transaction_id', 'tenant_id'], ['financial_transactions.id', 'financial_transactions.tenant_id'], name='fk_financial_allocations_transaction_tenant', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_financial_allocations')),
    sa.UniqueConstraint('id', 'tenant_id', name='uq_financial_allocations_id_tenant'),
    sa.UniqueConstraint('tenant_id', 'transaction_id', 'entry_id', name='uq_financial_allocations_transaction_entry')
    )
    op.create_index('ix_financial_allocations_tenant_entry', 'financial_allocations', ['tenant_id', 'entry_id'], unique=False)
    op.create_index(op.f('ix_financial_allocations_tenant_id'), 'financial_allocations', ['tenant_id'], unique=False)
    op.create_index('ix_financial_allocations_tenant_transaction', 'financial_allocations', ['tenant_id', 'transaction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_financial_allocations_tenant_transaction', table_name='financial_allocations')
    op.drop_index(op.f('ix_financial_allocations_tenant_id'), table_name='financial_allocations')
    op.drop_index('ix_financial_allocations_tenant_entry', table_name='financial_allocations')
    op.drop_table('financial_allocations')
    op.drop_index('ix_financial_entries_tenant_type_status', table_name='financial_entries')
    op.drop_index('ix_financial_entries_tenant_supplier', table_name='financial_entries')
    op.drop_index('ix_financial_entries_tenant_sales_order', table_name='financial_entries')
    op.drop_index('ix_financial_entries_tenant_purchase_order', table_name='financial_entries')
    op.drop_index(op.f('ix_financial_entries_tenant_id'), table_name='financial_entries')
    op.drop_index('ix_financial_entries_tenant_employee', table_name='financial_entries')
    op.drop_index('ix_financial_entries_tenant_due_date', table_name='financial_entries')
    op.drop_index('ix_financial_entries_tenant_customer', table_name='financial_entries')
    op.drop_index('ix_financial_entries_tenant_branch', table_name='financial_entries')
    op.drop_table('financial_entries')
    op.drop_index('ix_financial_transactions_tenant_type_status', table_name='financial_transactions')
    op.drop_index('ix_financial_transactions_tenant_occurred', table_name='financial_transactions')
    op.drop_index(op.f('ix_financial_transactions_tenant_id'), table_name='financial_transactions')
    op.drop_index('ix_financial_transactions_tenant_account', table_name='financial_transactions')
    op.drop_table('financial_transactions')
    op.drop_index('ix_financial_accounts_tenant_type', table_name='financial_accounts')
    op.drop_index(op.f('ix_financial_accounts_tenant_id'), table_name='financial_accounts')
    op.drop_index('ix_financial_accounts_tenant_branch', table_name='financial_accounts')
    op.drop_index('ix_financial_accounts_tenant_active', table_name='financial_accounts')
    op.drop_table('financial_accounts')
    # ### end Alembic commands ###
