"""add production assignments and checklist items

Revision ID: 6f217e7442e3
Revises: 69e086a75bdb
Create Date: 2026-08-08 09:22:18.117892

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "6f217e7442e3"
down_revision: str | Sequence[str] | None = "69e086a75bdb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "production_assignments",
        sa.Column("production_operation_id", sa.Uuid(), nullable=False),
        sa.Column("employee_id", sa.Uuid(), nullable=False),
        sa.Column("assigned_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("assigned_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("unassigned_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            (
                "(is_active = true AND unassigned_at IS NULL) "
                "OR "
                "(is_active = false AND unassigned_at IS NOT NULL)"
            ),
            name=op.f(
                "ck_production_assignments_active_state_valid"
            ),
        ),
        sa.CheckConstraint(
            "unassigned_at IS NULL OR unassigned_at >= assigned_at",
            name=op.f("ck_production_assignments_assignment_dates_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["assigned_by_user_id"], ["users.id"], name="fk_production_assignments_assigned_by_user"
        ),
        sa.ForeignKeyConstraint(
            ["employee_id", "tenant_id"],
            ["employees.id", "employees.tenant_id"],
            name="fk_production_assignments_employee_tenant",
        ),
        sa.ForeignKeyConstraint(
            ["production_operation_id", "tenant_id"],
            ["production_operations.id", "production_operations.tenant_id"],
            name="fk_production_assignments_operation_tenant",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_production_assignments_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_production_assignments")),
        sa.UniqueConstraint("id", "tenant_id", name="uq_production_assignments_id_tenant"),
    )
    op.create_index(
        "ix_production_assignments_tenant_active",
        "production_assignments",
        ["tenant_id", "is_active"],
        unique=False,
    )
    op.create_index(
        "ix_production_assignments_tenant_assigned",
        "production_assignments",
        ["tenant_id", "assigned_at"],
        unique=False,
    )
    op.create_index(
        "ix_production_assignments_tenant_employee",
        "production_assignments",
        ["tenant_id", "employee_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_production_assignments_tenant_id"),
        "production_assignments",
        ["tenant_id"],
        unique=False,
    )
    op.create_index(
        "ix_production_assignments_tenant_operation",
        "production_assignments",
        ["tenant_id", "production_operation_id"],
        unique=False,
    )
    op.create_index(
        "uq_production_assignments_active_employee",
        "production_assignments",
        ["tenant_id", "production_operation_id", "employee_id"],
        unique=True,
        postgresql_where=sa.text("is_active = true"),
        sqlite_where=sa.text("is_active = 1"),
    )
    op.create_table(
        "production_checklist_items",
        sa.Column("production_operation_id", sa.Uuid(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("is_required", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("is_applicable", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_by_employee_id", sa.Uuid(), nullable=True),
        sa.Column("notes", sa.String(length=4000), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "TRIM(title) <> ''", name=op.f("ck_production_checklist_items_title_not_blank")
        ),
        sa.CheckConstraint(
            "completed_by_employee_id IS NULL OR completed_at IS NOT NULL",
            name=op.f("ck_production_checklist_items_completion_employee_requires_date"),
        ),
        sa.CheckConstraint(
            "is_applicable = true OR (completed_at IS NULL AND completed_by_employee_id IS NULL)",
            name=op.f("ck_production_checklist_items_not_applicable_not_completed"),
        ),
        sa.CheckConstraint(
            "sequence > 0", name=op.f("ck_production_checklist_items_sequence_positive")
        ),
        sa.ForeignKeyConstraint(
            ["completed_by_employee_id", "tenant_id"],
            ["employees.id", "employees.tenant_id"],
            name="fk_production_checklist_items_employee_tenant",
        ),
        sa.ForeignKeyConstraint(
            ["production_operation_id", "tenant_id"],
            ["production_operations.id", "production_operations.tenant_id"],
            name="fk_production_checklist_items_operation_tenant",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_production_checklist_items_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_production_checklist_items")),
        sa.UniqueConstraint("id", "tenant_id", name="uq_production_checklist_items_id_tenant"),
        sa.UniqueConstraint(
            "production_operation_id",
            "sequence",
            name="uq_production_checklist_items_operation_sequence",
        ),
    )
    op.create_index(
        "ix_production_checklist_items_tenant_applicable",
        "production_checklist_items",
        ["tenant_id", "is_applicable"],
        unique=False,
    )
    op.create_index(
        "ix_production_checklist_items_tenant_completed_by",
        "production_checklist_items",
        ["tenant_id", "completed_by_employee_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_production_checklist_items_tenant_id"),
        "production_checklist_items",
        ["tenant_id"],
        unique=False,
    )
    op.create_index(
        "ix_production_checklist_items_tenant_operation",
        "production_checklist_items",
        ["tenant_id", "production_operation_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_production_checklist_items_tenant_operation", table_name="production_checklist_items"
    )
    op.drop_index(
        op.f("ix_production_checklist_items_tenant_id"), table_name="production_checklist_items"
    )
    op.drop_index(
        "ix_production_checklist_items_tenant_completed_by", table_name="production_checklist_items"
    )
    op.drop_index(
        "ix_production_checklist_items_tenant_applicable", table_name="production_checklist_items"
    )
    op.drop_table("production_checklist_items")
    op.drop_index(
        "uq_production_assignments_active_employee",
        table_name="production_assignments",
        postgresql_where=sa.text("is_active = true"),
        sqlite_where=sa.text("is_active = 1"),
    )
    op.drop_index("ix_production_assignments_tenant_operation", table_name="production_assignments")
    op.drop_index(op.f("ix_production_assignments_tenant_id"), table_name="production_assignments")
    op.drop_index("ix_production_assignments_tenant_employee", table_name="production_assignments")
    op.drop_index("ix_production_assignments_tenant_assigned", table_name="production_assignments")
    op.drop_index("ix_production_assignments_tenant_active", table_name="production_assignments")
    op.drop_table("production_assignments")
    # ### end Alembic commands ###
