"""create sales core

Revision ID: 9189ddfdd4b1
Revises: 51b4d66e1411
Create Date: 2026-08-07 17:32:02.478709

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "9189ddfdd4b1"
down_revision: str | Sequence[str] | None = "51b4d66e1411"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_unique_constraint("uq_clientes_id_tenant", "clientes", ["id", "tenant_id"])
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sales_quotes",
        sa.Column("customer_id", sa.Integer(), nullable=False),
        sa.Column("branch_id", sa.Uuid(), nullable=True),
        sa.Column("salesperson_employee_id", sa.Uuid(), nullable=True),
        sa.Column("code", sa.String(length=100), nullable=False),
        sa.Column(
            "status", sa.String(length=30), server_default=sa.text("'DRAFT'"), nullable=False
        ),
        sa.Column("project_name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=4000), nullable=True),
        sa.Column("issued_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("valid_until", sa.Date(), nullable=True),
        sa.Column("expected_delivery_at", sa.Date(), nullable=True),
        sa.Column("payment_terms", sa.String(length=2000), nullable=True),
        sa.Column("notes", sa.String(length=4000), nullable=True),
        sa.Column(
            "material_cost",
            sa.Numeric(precision=18, scale=6),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "labor_cost",
            sa.Numeric(precision=18, scale=6),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "transport_cost",
            sa.Numeric(precision=18, scale=6),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "other_cost",
            sa.Numeric(precision=18, scale=6),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "tax_amount",
            sa.Numeric(precision=18, scale=6),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "discount_amount",
            sa.Numeric(precision=18, scale=6),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "proposed_amount",
            sa.Numeric(precision=18, scale=6),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column("approved_amount", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("rejected_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expired_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "(status <> 'APPROVED') OR (approved_amount IS NOT NULL AND approved_at IS NOT NULL)",
            name=op.f("ck_sales_quotes_approved_state_valid"),
        ),
        sa.CheckConstraint(
            "(status <> 'CANCELLED') OR cancelled_at IS NOT NULL",
            name=op.f("ck_sales_quotes_cancelled_state_valid"),
        ),
        sa.CheckConstraint(
            "(status <> 'EXPIRED') OR expired_at IS NOT NULL",
            name=op.f("ck_sales_quotes_expired_state_valid"),
        ),
        sa.CheckConstraint(
            "(status <> 'REJECTED') OR rejected_at IS NOT NULL",
            name=op.f("ck_sales_quotes_rejected_state_valid"),
        ),
        sa.CheckConstraint("TRIM(code) <> ''", name=op.f("ck_sales_quotes_code_not_blank")),
        sa.CheckConstraint(
            "TRIM(project_name) <> ''", name=op.f("ck_sales_quotes_project_name_not_blank")
        ),
        sa.CheckConstraint(
            "status IN ("
            "'DRAFT', 'SENT', 'NEGOTIATION', "
            "'APPROVED', 'REJECTED', 'CANCELLED', "
            "'EXPIRED'"
            ")",
            name=op.f("ck_sales_quotes_status_valid"),
        ),
        sa.CheckConstraint(
            "approved_amount IS NULL OR approved_amount > 0",
            name=op.f("ck_sales_quotes_approved_amount_positive"),
        ),
        sa.CheckConstraint(
            "discount_amount >= 0", name=op.f("ck_sales_quotes_discount_amount_non_negative")
        ),
        sa.CheckConstraint("labor_cost >= 0", name=op.f("ck_sales_quotes_labor_cost_non_negative")),
        sa.CheckConstraint(
            "material_cost >= 0", name=op.f("ck_sales_quotes_material_cost_non_negative")
        ),
        sa.CheckConstraint("other_cost >= 0", name=op.f("ck_sales_quotes_other_cost_non_negative")),
        sa.CheckConstraint(
            "proposed_amount >= 0", name=op.f("ck_sales_quotes_proposed_amount_non_negative")
        ),
        sa.CheckConstraint("tax_amount >= 0", name=op.f("ck_sales_quotes_tax_amount_non_negative")),
        sa.CheckConstraint(
            "transport_cost >= 0", name=op.f("ck_sales_quotes_transport_cost_non_negative")
        ),
        sa.CheckConstraint(
            "valid_until IS NULL OR issued_at IS NULL OR valid_until >= CAST(issued_at AS DATE)",
            name=op.f("ck_sales_quotes_validity_dates_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["branch_id", "tenant_id"],
            ["branches.id", "branches.tenant_id"],
            name="fk_sales_quotes_branch_tenant",
        ),
        sa.ForeignKeyConstraint(
            ["customer_id", "tenant_id"],
            ["clientes.id", "clientes.tenant_id"],
            name="fk_sales_quotes_customer_tenant",
        ),
        sa.ForeignKeyConstraint(
            ["salesperson_employee_id", "tenant_id"],
            ["employees.id", "employees.tenant_id"],
            name="fk_sales_quotes_salesperson_tenant",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_sales_quotes_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sales_quotes")),
        sa.UniqueConstraint(
            "id", "customer_id", "tenant_id", name="uq_sales_quotes_id_customer_tenant"
        ),
        sa.UniqueConstraint("id", "tenant_id", name="uq_sales_quotes_id_tenant"),
        sa.UniqueConstraint("tenant_id", "code", name="uq_sales_quotes_tenant_code"),
    )
    op.create_index(
        "ix_sales_quotes_tenant_branch", "sales_quotes", ["tenant_id", "branch_id"], unique=False
    )
    op.create_index(
        "ix_sales_quotes_tenant_customer",
        "sales_quotes",
        ["tenant_id", "customer_id"],
        unique=False,
    )
    op.create_index(op.f("ix_sales_quotes_tenant_id"), "sales_quotes", ["tenant_id"], unique=False)
    op.create_index(
        "ix_sales_quotes_tenant_issued", "sales_quotes", ["tenant_id", "issued_at"], unique=False
    )
    op.create_index(
        "ix_sales_quotes_tenant_salesperson",
        "sales_quotes",
        ["tenant_id", "salesperson_employee_id"],
        unique=False,
    )
    op.create_index(
        "ix_sales_quotes_tenant_status", "sales_quotes", ["tenant_id", "status"], unique=False
    )
    op.create_table(
        "sales_orders",
        sa.Column("source_quote_id", sa.Uuid(), nullable=False),
        sa.Column("customer_id", sa.Integer(), nullable=False),
        sa.Column("branch_id", sa.Uuid(), nullable=True),
        sa.Column("salesperson_employee_id", sa.Uuid(), nullable=True),
        sa.Column("code", sa.String(length=100), nullable=False),
        sa.Column("status", sa.String(length=30), server_default=sa.text("'OPEN'"), nullable=False),
        sa.Column("ordered_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("project_name_snapshot", sa.String(length=255), nullable=True),
        sa.Column("expected_delivery_at", sa.Date(), nullable=True),
        sa.Column("total_amount", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("payment_terms_snapshot", sa.String(length=2000), nullable=True),
        sa.Column("delivery_address_snapshot", sa.String(length=2000), nullable=True),
        sa.Column("notes", sa.String(length=4000), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "(status <> 'CANCELLED') OR cancelled_at IS NOT NULL",
            name=op.f("ck_sales_orders_cancelled_state_valid"),
        ),
        sa.CheckConstraint(
            "(status <> 'CLOSED') OR closed_at IS NOT NULL",
            name=op.f("ck_sales_orders_closed_state_valid"),
        ),
        sa.CheckConstraint(
            "(status <> 'DELIVERED') OR delivered_at IS NOT NULL",
            name=op.f("ck_sales_orders_delivered_state_valid"),
        ),
        sa.CheckConstraint("TRIM(code) <> ''", name=op.f("ck_sales_orders_code_not_blank")),
        sa.CheckConstraint(
            "status IN ("
            "'OPEN', 'IN_PRODUCTION', "
            "'READY_FOR_DELIVERY', 'DELIVERED', "
            "'CLOSED', 'CANCELLED'"
            ")",
            name=op.f("ck_sales_orders_status_valid"),
        ),
        sa.CheckConstraint("total_amount > 0", name=op.f("ck_sales_orders_total_amount_positive")),
        sa.ForeignKeyConstraint(
            ["branch_id", "tenant_id"],
            ["branches.id", "branches.tenant_id"],
            name="fk_sales_orders_branch_tenant",
        ),
        sa.ForeignKeyConstraint(
            ["customer_id", "tenant_id"],
            ["clientes.id", "clientes.tenant_id"],
            name="fk_sales_orders_customer_tenant",
        ),
        sa.ForeignKeyConstraint(
            ["salesperson_employee_id", "tenant_id"],
            ["employees.id", "employees.tenant_id"],
            name="fk_sales_orders_salesperson_tenant",
        ),
        sa.ForeignKeyConstraint(
            ["source_quote_id", "customer_id", "tenant_id"],
            ["sales_quotes.id", "sales_quotes.customer_id", "sales_quotes.tenant_id"],
            name="fk_sales_orders_quote_customer_tenant",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_sales_orders_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sales_orders")),
        sa.UniqueConstraint(
            "id", "source_quote_id", "tenant_id", name="uq_sales_orders_id_quote_tenant"
        ),
        sa.UniqueConstraint("id", "tenant_id", name="uq_sales_orders_id_tenant"),
        sa.UniqueConstraint("tenant_id", "code", name="uq_sales_orders_tenant_code"),
        sa.UniqueConstraint(
            "tenant_id", "source_quote_id", name="uq_sales_orders_tenant_source_quote"
        ),
    )
    op.create_index(
        "ix_sales_orders_tenant_branch", "sales_orders", ["tenant_id", "branch_id"], unique=False
    )
    op.create_index(
        "ix_sales_orders_tenant_customer",
        "sales_orders",
        ["tenant_id", "customer_id"],
        unique=False,
    )
    op.create_index(op.f("ix_sales_orders_tenant_id"), "sales_orders", ["tenant_id"], unique=False)
    op.create_index(
        "ix_sales_orders_tenant_ordered", "sales_orders", ["tenant_id", "ordered_at"], unique=False
    )
    op.create_index(
        "ix_sales_orders_tenant_salesperson",
        "sales_orders",
        ["tenant_id", "salesperson_employee_id"],
        unique=False,
    )
    op.create_index(
        "ix_sales_orders_tenant_status", "sales_orders", ["tenant_id", "status"], unique=False
    )
    op.create_table(
        "sales_quote_items",
        sa.Column("sales_quote_id", sa.Uuid(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("material_id", sa.Uuid(), nullable=True),
        sa.Column("service_id", sa.Uuid(), nullable=True),
        sa.Column("description_snapshot", sa.String(length=2000), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column(
            "discount_amount",
            sa.Numeric(precision=18, scale=6),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "TRIM(description_snapshot) <> ''",
            name=op.f("ck_sales_quote_items_description_not_blank"),
        ),
        sa.CheckConstraint(
            "NOT (material_id IS NOT NULL AND service_id IS NOT NULL)",
            name=op.f("ck_sales_quote_items_catalog_reference_exclusive"),
        ),
        sa.CheckConstraint(
            "discount_amount <= quantity * unit_price",
            name=op.f("ck_sales_quote_items_discount_not_above_gross"),
        ),
        sa.CheckConstraint(
            "discount_amount >= 0", name=op.f("ck_sales_quote_items_discount_non_negative")
        ),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_sales_quote_items_quantity_positive")),
        sa.CheckConstraint("sequence > 0", name=op.f("ck_sales_quote_items_sequence_positive")),
        sa.CheckConstraint(
            "unit_price >= 0", name=op.f("ck_sales_quote_items_unit_price_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["material_id", "tenant_id"],
            ["materials.id", "materials.tenant_id"],
            name="fk_sales_quote_items_material_tenant",
        ),
        sa.ForeignKeyConstraint(
            ["sales_quote_id", "tenant_id"],
            ["sales_quotes.id", "sales_quotes.tenant_id"],
            name="fk_sales_quote_items_quote_tenant",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["service_id", "tenant_id"],
            ["services.id", "services.tenant_id"],
            name="fk_sales_quote_items_service_tenant",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_sales_quote_items_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sales_quote_items")),
        sa.UniqueConstraint(
            "id", "sales_quote_id", "tenant_id", name="uq_sales_quote_items_id_quote_tenant"
        ),
        sa.UniqueConstraint("id", "tenant_id", name="uq_sales_quote_items_id_tenant"),
        sa.UniqueConstraint(
            "sales_quote_id", "sequence", name="uq_sales_quote_items_quote_sequence"
        ),
    )
    op.create_index(
        op.f("ix_sales_quote_items_tenant_id"), "sales_quote_items", ["tenant_id"], unique=False
    )
    op.create_index(
        "ix_sales_quote_items_tenant_material",
        "sales_quote_items",
        ["tenant_id", "material_id"],
        unique=False,
    )
    op.create_index(
        "ix_sales_quote_items_tenant_quote",
        "sales_quote_items",
        ["tenant_id", "sales_quote_id"],
        unique=False,
    )
    op.create_index(
        "ix_sales_quote_items_tenant_service",
        "sales_quote_items",
        ["tenant_id", "service_id"],
        unique=False,
    )
    op.create_table(
        "sales_order_items",
        sa.Column("sales_order_id", sa.Uuid(), nullable=False),
        sa.Column("source_quote_id", sa.Uuid(), nullable=False),
        sa.Column("source_quote_item_id", sa.Uuid(), nullable=True),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("material_id", sa.Uuid(), nullable=True),
        sa.Column("service_id", sa.Uuid(), nullable=True),
        sa.Column("description_snapshot", sa.String(length=2000), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column(
            "discount_amount",
            sa.Numeric(precision=18, scale=6),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "TRIM(description_snapshot) <> ''",
            name=op.f("ck_sales_order_items_description_not_blank"),
        ),
        sa.CheckConstraint(
            "NOT (material_id IS NOT NULL AND service_id IS NOT NULL)",
            name=op.f("ck_sales_order_items_catalog_reference_exclusive"),
        ),
        sa.CheckConstraint(
            "discount_amount <= quantity * unit_price",
            name=op.f("ck_sales_order_items_discount_not_above_gross"),
        ),
        sa.CheckConstraint(
            "discount_amount >= 0", name=op.f("ck_sales_order_items_discount_non_negative")
        ),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_sales_order_items_quantity_positive")),
        sa.CheckConstraint("sequence > 0", name=op.f("ck_sales_order_items_sequence_positive")),
        sa.CheckConstraint(
            "unit_price >= 0", name=op.f("ck_sales_order_items_unit_price_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["material_id", "tenant_id"],
            ["materials.id", "materials.tenant_id"],
            name="fk_sales_order_items_material_tenant",
        ),
        sa.ForeignKeyConstraint(
            ["sales_order_id", "source_quote_id", "tenant_id"],
            ["sales_orders.id", "sales_orders.source_quote_id", "sales_orders.tenant_id"],
            name="fk_sales_order_items_order_quote_tenant",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["service_id", "tenant_id"],
            ["services.id", "services.tenant_id"],
            name="fk_sales_order_items_service_tenant",
        ),
        sa.ForeignKeyConstraint(
            ["source_quote_item_id", "source_quote_id", "tenant_id"],
            [
                "sales_quote_items.id",
                "sales_quote_items.sales_quote_id",
                "sales_quote_items.tenant_id",
            ],
            name="fk_sales_order_items_quote_item_quote_tenant",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_sales_order_items_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sales_order_items")),
        sa.UniqueConstraint(
            "sales_order_id", "sequence", name="uq_sales_order_items_order_sequence"
        ),
    )
    op.create_index(
        op.f("ix_sales_order_items_tenant_id"), "sales_order_items", ["tenant_id"], unique=False
    )
    op.create_index(
        "ix_sales_order_items_tenant_material",
        "sales_order_items",
        ["tenant_id", "material_id"],
        unique=False,
    )
    op.create_index(
        "ix_sales_order_items_tenant_order",
        "sales_order_items",
        ["tenant_id", "sales_order_id"],
        unique=False,
    )
    op.create_index(
        "ix_sales_order_items_tenant_quote_item",
        "sales_order_items",
        ["tenant_id", "source_quote_item_id"],
        unique=False,
    )
    op.create_index(
        "ix_sales_order_items_tenant_service",
        "sales_order_items",
        ["tenant_id", "service_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_sales_order_items_tenant_service", table_name="sales_order_items")
    op.drop_index("ix_sales_order_items_tenant_quote_item", table_name="sales_order_items")
    op.drop_index("ix_sales_order_items_tenant_order", table_name="sales_order_items")
    op.drop_index("ix_sales_order_items_tenant_material", table_name="sales_order_items")
    op.drop_index(op.f("ix_sales_order_items_tenant_id"), table_name="sales_order_items")
    op.drop_table("sales_order_items")
    op.drop_index("ix_sales_quote_items_tenant_service", table_name="sales_quote_items")
    op.drop_index("ix_sales_quote_items_tenant_quote", table_name="sales_quote_items")
    op.drop_index("ix_sales_quote_items_tenant_material", table_name="sales_quote_items")
    op.drop_index(op.f("ix_sales_quote_items_tenant_id"), table_name="sales_quote_items")
    op.drop_table("sales_quote_items")
    op.drop_index("ix_sales_orders_tenant_status", table_name="sales_orders")
    op.drop_index("ix_sales_orders_tenant_salesperson", table_name="sales_orders")
    op.drop_index("ix_sales_orders_tenant_ordered", table_name="sales_orders")
    op.drop_index(op.f("ix_sales_orders_tenant_id"), table_name="sales_orders")
    op.drop_index("ix_sales_orders_tenant_customer", table_name="sales_orders")
    op.drop_index("ix_sales_orders_tenant_branch", table_name="sales_orders")
    op.drop_table("sales_orders")
    op.drop_index("ix_sales_quotes_tenant_status", table_name="sales_quotes")
    op.drop_index("ix_sales_quotes_tenant_salesperson", table_name="sales_quotes")
    op.drop_index("ix_sales_quotes_tenant_issued", table_name="sales_quotes")
    op.drop_index(op.f("ix_sales_quotes_tenant_id"), table_name="sales_quotes")
    op.drop_index("ix_sales_quotes_tenant_customer", table_name="sales_quotes")
    op.drop_index("ix_sales_quotes_tenant_branch", table_name="sales_quotes")
    op.drop_table("sales_quotes")
    op.drop_constraint("uq_clientes_id_tenant", "clientes", type_="unique")
    # ### end Alembic commands ###
