"""create branch foundation

Revision ID: 9fb2267cbba8
Revises: d3f6a1c8e902
Create Date: 2026-08-07 11:10:12.679721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fb2267cbba8'
down_revision: Union[str, Sequence[str], None] = 'd3f6a1c8e902'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('branches',
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('legal_name', sa.String(length=255), nullable=True),
    sa.Column('document_number', sa.String(length=20), nullable=True),
    sa.Column('is_headquarters', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("TRIM(code) <> ''", name=op.f('ck_branches_code_not_blank')),
    sa.CheckConstraint("TRIM(name) <> ''", name=op.f('ck_branches_name_not_blank')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_branches_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_branches')),
    sa.UniqueConstraint('id', 'tenant_id', name='uq_branches_id_tenant')
    )
    op.create_index('ix_branches_tenant_active', 'branches', ['tenant_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_branches_tenant_id'), 'branches', ['tenant_id'], unique=False)
    op.create_index('uq_branches_tenant_code_normalized', 'branches', ['tenant_id', sa.literal_column('lower(TRIM(BOTH FROM code))')], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_branches_tenant_code_normalized', table_name='branches')
    op.drop_index(op.f('ix_branches_tenant_id'), table_name='branches')
    op.drop_index('ix_branches_tenant_active', table_name='branches')
    op.drop_table('branches')
    # ### end Alembic commands ###
