"""Create identity and authorization foundation.

Revision ID: d3f6a1c8e902
Revises: a81c5e7d2f34
Create Date: 2026-08-06
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

revision: str = "d3f6a1c8e902"
down_revision: str | None = "a81c5e7d2f34"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Create application identities and authorization structures."""

    op.create_table(
        "users",
        sa.Column(
            "id",
            sa.Uuid(as_uuid=True),
            nullable=False,
        ),
        sa.Column(
            "auth_user_id",
            sa.Uuid(as_uuid=True),
            nullable=False,
        ),
        sa.Column(
            "email",
            sa.String(length=320),
            nullable=False,
        ),
        sa.Column(
            "display_name",
            sa.String(length=255),
            nullable=False,
        ),
        sa.Column(
            "phone",
            sa.String(length=30),
            nullable=True,
        ),
        sa.Column(
            "last_login_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "deleted_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "row_version",
            sa.Integer(),
            server_default=sa.text("1"),
            nullable=False,
        ),
        sa.Column(
            "is_active",
            sa.Boolean(),
            server_default=sa.true(),
            nullable=False,
        ),
        sa.CheckConstraint(
            "TRIM(email) <> ''",
            name=op.f(
                "ck_users_email_not_blank"
            ),
        ),
        sa.CheckConstraint(
            "TRIM(display_name) <> ''",
            name=op.f(
                "ck_users_display_name_not_blank"
            ),
        ),
        sa.CheckConstraint(
            "row_version >= 1",
            name=op.f(
                "ck_users_row_version_positive"
            ),
        ),
        sa.PrimaryKeyConstraint(
            "id",
            name=op.f("pk_users"),
        ),
        sa.UniqueConstraint(
            "auth_user_id",
            name=op.f(
                "uq_users_auth_user_id"
            ),
        ),
    )

    op.create_index(
        "ix_users_active_deleted",
        "users",
        [
            "is_active",
            "deleted_at",
        ],
        unique=False,
    )

    op.execute(
        sa.text(
            """
            CREATE UNIQUE INDEX
                uq_users_email_normalized
            ON users (
                LOWER(TRIM(email))
            )
            """
        )
    )

    op.create_table(
        "tenant_memberships",
        sa.Column(
            "id",
            sa.Uuid(as_uuid=True),
            nullable=False,
        ),
        sa.Column(
            "tenant_id",
            sa.Uuid(as_uuid=True),
            nullable=False,
        ),
        sa.Column(
            "user_id",
            sa.Uuid(as_uuid=True),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.String(length=20),
            server_default=sa.text(
                "'INVITED'"
            ),
            nullable=False,
        ),
        sa.Column(
            "invited_at",
            sa.DateTime(timezone=True),
            server_default=sa.text(
                "CURRENT_TIMESTAMP"
            ),
            nullable=False,
        ),
        sa.Column(
            "joined_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "suspended_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "revoked_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text(
                "CURRENT_TIMESTAMP"
            ),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text(
                "CURRENT_TIMESTAMP"
            ),
            nullable=False,
        ),
        sa.Column(
            "row_version",
            sa.Integer(),
            server_default=sa.text("1"),
            nullable=False,
        ),
        sa.CheckConstraint(
            (
                "status IN "
                "('INVITED', 'ACTIVE', "
                "'SUSPENDED', 'REVOKED')"
            ),
            name=op.f(
                "ck_tenant_memberships_status_valid"
            ),
        ),
        sa.CheckConstraint(
            "row_version >= 1",
            name=op.f(
                "ck_tenant_memberships_"
                "row_version_positive"
            ),
        ),
        sa.ForeignKeyConstraint(
            [
                "tenant_id",
            ],
            [
                "tenants.id",
            ],
            name=op.f(
                "fk_tenant_memberships_"
                "tenant_id_tenants"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            [
                "user_id",
            ],
            [
                "users.id",
            ],
            name=op.f(
                "fk_tenant_memberships_"
                "user_id_users"
            ),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "id",
            name=op.f(
                "pk_tenant_memberships"
            ),
        ),
        sa.UniqueConstraint(
            "tenant_id",
            "user_id",
            name=op.f(
                "uq_tenant_memberships_tenant_user"
            ),
        ),
        sa.UniqueConstraint(
            "id",
            "tenant_id",
            name=op.f(
                "uq_tenant_memberships_id_tenant"
            ),
        ),
    )

    op.create_index(
        "ix_tenant_memberships_tenant_status",
        "tenant_memberships",
        [
            "tenant_id",
            "status",
        ],
        unique=False,
    )

    op.create_index(
        "ix_tenant_memberships_user_id",
        "tenant_memberships",
        [
            "user_id",
        ],
        unique=False,
    )

    op.create_table(
        "access_profiles",
        sa.Column(
            "id",
            sa.Uuid(as_uuid=True),
            nullable=False,
        ),
        sa.Column(
            "tenant_id",
            sa.Uuid(as_uuid=True),
            nullable=False,
        ),
        sa.Column(
            "code",
            sa.String(length=100),
            nullable=False,
        ),
        sa.Column(
            "name",
            sa.String(length=255),
            nullable=False,
        ),
        sa.Column(
            "description",
            sa.Text(),
            nullable=True,
        ),
        sa.Column(
            "is_system",
            sa.Boolean(),
            server_default=sa.false(),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text(
                "CURRENT_TIMESTAMP"
            ),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text(
                "CURRENT_TIMESTAMP"
            ),
            nullable=False,
        ),
        sa.Column(
            "deleted_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "row_version",
            sa.Integer(),
            server_default=sa.text("1"),
            nullable=False,
        ),
        sa.Column(
            "is_active",
            sa.Boolean(),
            server_default=sa.true(),
            nullable=False,
        ),
        sa.CheckConstraint(
            "TRIM(code) <> ''",
            name=op.f(
                "ck_access_profiles_code_not_blank"
            ),
        ),
        sa.CheckConstraint(
            "TRIM(name) <> ''",
            name=op.f(
                "ck_access_profiles_name_not_blank"
            ),
        ),
        sa.CheckConstraint(
            "row_version >= 1",
            name=op.f(
                "ck_access_profiles_"
                "row_version_positive"
            ),
        ),
        sa.ForeignKeyConstraint(
            [
                "tenant_id",
            ],
            [
                "tenants.id",
            ],
            name=op.f(
                "fk_access_profiles_"
                "tenant_id_tenants"
            ),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "id",
            name=op.f(
                "pk_access_profiles"
            ),
        ),
        sa.UniqueConstraint(
            "id",
            "tenant_id",
            name=op.f(
                "uq_access_profiles_id_tenant"
            ),
        ),
    )

    op.create_index(
        "ix_access_profiles_tenant_active",
        "access_profiles",
        [
            "tenant_id",
            "is_active",
        ],
        unique=False,
    )

    op.execute(
        sa.text(
            """
            CREATE UNIQUE INDEX
                uq_access_profiles_tenant_code_normalized
            ON access_profiles (
                tenant_id,
                LOWER(TRIM(code))
            )
            """
        )
    )

    op.create_table(
        "permissions",
        sa.Column(
            "id",
            sa.Uuid(as_uuid=True),
            nullable=False,
        ),
        sa.Column(
            "code",
            sa.String(length=150),
            nullable=False,
        ),
        sa.Column(
            "name",
            sa.String(length=255),
            nullable=False,
        ),
        sa.Column(
            "module",
            sa.String(length=100),
            nullable=False,
        ),
        sa.Column(
            "resource",
            sa.String(length=100),
            nullable=False,
        ),
        sa.Column(
            "action",
            sa.String(length=100),
            nullable=False,
        ),
        sa.Column(
            "description",
            sa.Text(),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text(
                "CURRENT_TIMESTAMP"
            ),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text(
                "CURRENT_TIMESTAMP"
            ),
            nullable=False,
        ),
        sa.Column(
            "is_active",
            sa.Boolean(),
            server_default=sa.true(),
            nullable=False,
        ),
        sa.CheckConstraint(
            "TRIM(code) <> ''",
            name=op.f(
                "ck_permissions_code_not_blank"
            ),
        ),
        sa.CheckConstraint(
            "TRIM(name) <> ''",
            name=op.f(
                "ck_permissions_name_not_blank"
            ),
        ),
        sa.CheckConstraint(
            "TRIM(module) <> ''",
            name=op.f(
                "ck_permissions_module_not_blank"
            ),
        ),
        sa.CheckConstraint(
            "TRIM(resource) <> ''",
            name=op.f(
                "ck_permissions_resource_not_blank"
            ),
        ),
        sa.CheckConstraint(
            "TRIM(action) <> ''",
            name=op.f(
                "ck_permissions_action_not_blank"
            ),
        ),
        sa.PrimaryKeyConstraint(
            "id",
            name=op.f(
                "pk_permissions"
            ),
        ),
    )

    op.create_index(
        "ix_permissions_module_resource",
        "permissions",
        [
            "module",
            "resource",
        ],
        unique=False,
    )

    op.execute(
        sa.text(
            """
            CREATE UNIQUE INDEX
                uq_permissions_code_normalized
            ON permissions (
                LOWER(TRIM(code))
            )
            """
        )
    )

    op.create_table(
        "access_profile_permissions",
        sa.Column(
            "access_profile_id",
            sa.Uuid(as_uuid=True),
            nullable=False,
        ),
        sa.Column(
            "permission_id",
            sa.Uuid(as_uuid=True),
            nullable=False,
        ),
        sa.Column(
            "granted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text(
                "CURRENT_TIMESTAMP"
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            [
                "access_profile_id",
            ],
            [
                "access_profiles.id",
            ],
            name=op.f(
                "fk_access_profile_permissions_"
                "access_profile_id_access_profiles"
            ),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            [
                "permission_id",
            ],
            [
                "permissions.id",
            ],
            name=op.f(
                "fk_access_profile_permissions_"
                "permission_id_permissions"
            ),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "access_profile_id",
            "permission_id",
            name=op.f(
                "pk_access_profile_permissions"
            ),
        ),
    )

    op.create_table(
        "tenant_membership_profiles",
        sa.Column(
            "tenant_id",
            sa.Uuid(as_uuid=True),
            nullable=False,
        ),
        sa.Column(
            "membership_id",
            sa.Uuid(as_uuid=True),
            nullable=False,
        ),
        sa.Column(
            "access_profile_id",
            sa.Uuid(as_uuid=True),
            nullable=False,
        ),
        sa.Column(
            "assigned_at",
            sa.DateTime(timezone=True),
            server_default=sa.text(
                "CURRENT_TIMESTAMP"
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            [
                "membership_id",
                "tenant_id",
            ],
            [
                "tenant_memberships.id",
                "tenant_memberships.tenant_id",
            ],
            name=op.f(
                "fk_tenant_membership_profiles_"
                "membership_tenant"
            ),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            [
                "access_profile_id",
                "tenant_id",
            ],
            [
                "access_profiles.id",
                "access_profiles.tenant_id",
            ],
            name=op.f(
                "fk_tenant_membership_profiles_"
                "profile_tenant"
            ),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "tenant_id",
            "membership_id",
            "access_profile_id",
            name=op.f(
                "pk_tenant_membership_profiles"
            ),
        ),
    )

    op.create_index(
        "ix_tenant_membership_profiles_profile",
        "tenant_membership_profiles",
        [
            "access_profile_id",
        ],
        unique=False,
    )

    op.create_table(
        "tenant_membership_permission_overrides",
        sa.Column(
            "tenant_id",
            sa.Uuid(as_uuid=True),
            nullable=False,
        ),
        sa.Column(
            "membership_id",
            sa.Uuid(as_uuid=True),
            nullable=False,
        ),
        sa.Column(
            "permission_id",
            sa.Uuid(as_uuid=True),
            nullable=False,
        ),
        sa.Column(
            "effect",
            sa.String(length=10),
            nullable=False,
        ),
        sa.Column(
            "granted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text(
                "CURRENT_TIMESTAMP"
            ),
            nullable=False,
        ),
        sa.CheckConstraint(
            "effect IN ('ALLOW', 'DENY')",
            name=op.f(
                "ck_tenant_membership_permission_"
                "overrides_effect_valid"
            ),
        ),
        sa.ForeignKeyConstraint(
            [
                "membership_id",
                "tenant_id",
            ],
            [
                "tenant_memberships.id",
                "tenant_memberships.tenant_id",
            ],
            name=op.f(
                "fk_tenant_membership_permission_"
                "overrides_membership_tenant"
            ),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            [
                "permission_id",
            ],
            [
                "permissions.id",
            ],
            name=op.f(
                "fk_tenant_membership_permission_"
                "overrides_permission_id_permissions"
            ),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "tenant_id",
            "membership_id",
            "permission_id",
            name=op.f(
                "pk_tenant_membership_permission_overrides"
            ),
        ),
    )

    op.create_index(
        (
            "ix_tenant_membership_permission_"
            "overrides_permission"
        ),
        "tenant_membership_permission_overrides",
        [
            "permission_id",
        ],
        unique=False,
    )


def downgrade() -> None:
    """Remove identity and authorization structures."""

    op.drop_index(
        (
            "ix_tenant_membership_permission_"
            "overrides_permission"
        ),
        table_name=(
            "tenant_membership_permission_overrides"
        ),
    )

    op.drop_table(
        "tenant_membership_permission_overrides"
    )

    op.drop_index(
        "ix_tenant_membership_profiles_profile",
        table_name="tenant_membership_profiles",
    )

    op.drop_table(
        "tenant_membership_profiles"
    )

    op.drop_table(
        "access_profile_permissions"
    )

    op.execute(
        sa.text(
            """
            DROP INDEX IF EXISTS
                uq_permissions_code_normalized
            """
        )
    )

    op.drop_index(
        "ix_permissions_module_resource",
        table_name="permissions",
    )

    op.drop_table(
        "permissions"
    )

    op.execute(
        sa.text(
            """
            DROP INDEX IF EXISTS
                uq_access_profiles_tenant_code_normalized
            """
        )
    )

    op.drop_index(
        "ix_access_profiles_tenant_active",
        table_name="access_profiles",
    )

    op.drop_table(
        "access_profiles"
    )

    op.drop_index(
        "ix_tenant_memberships_user_id",
        table_name="tenant_memberships",
    )

    op.drop_index(
        "ix_tenant_memberships_tenant_status",
        table_name="tenant_memberships",
    )

    op.drop_table(
        "tenant_memberships"
    )

    op.execute(
        sa.text(
            """
            DROP INDEX IF EXISTS
                uq_users_email_normalized
            """
        )
    )

    op.drop_index(
        "ix_users_active_deleted",
        table_name="users",
    )

    op.drop_table(
        "users"
    )